### PR TITLE
do aggressive restarts

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Comment by haampie** [comment]
@electronic-structure run

```yaml
spec: sirius@develop +scalapack
```

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark submitted:</summary>

```json
{
    "reference": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "haampie/SIRIUS",
        "sha": "a923c3c8853d846138a8b9a9c096494004b8d208"
    },
    "current": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "haampie/SIRIUS",
        "sha": "40e9e6046ebfdd2424926f76cb043caae175bee0"
    },
    "report_to": {
        "repository": "haampie/SIRIUS",
        "type": "pr",
        "issue": 4
    }
}

```
</details>

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/15/40e9e60_vs_a923c3c/

```diff
  Si63Ge ───────────────────  72.24 s  →  72.47 s   (+0.32%)
  SiO2-ANA-kpoint-parallel ─ 132.90 s  → 129.08 s   (-2.87%)
  SiO2-ANA-band-parallel ─── 242.74 s  → 223.07 s   (-8.10%)
```

**Comment by haampie** [comment]
@electronic-structure run

```yaml
spec: sirius@develop +scalapack
```

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark 0f71b6c1-e2ad-4273-b5fb-3fec3c037488 submitted:</summary>

```json
{
    "id": "0f71b6c1-e2ad-4273-b5fb-3fec3c037488",
    "reference": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "haampie/SIRIUS",
        "sha": "a923c3c8853d846138a8b9a9c096494004b8d208",
        "build": true
    },
    "current": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "haampie/SIRIUS",
        "sha": "adff978c05fe0b8ea67eae5f2174d5616f15acab",
        "build": true
    },
    "report_to": {
        "repository": "haampie/SIRIUS",
        "type": "pr",
        "issue": 4
    }
}

```
</details>

To trigger benchmarks again using cached binaries, use
```yaml
id: "0f71b6c1-e2ad-4273-b5fb-3fec3c037488"
```

**Comment by haampie** [comment]
@electronic-structure run

```yaml
id: "0f71b6c1-e2ad-4273-b5fb-3fec3c037488"

current:
  cmd: sirius.scf --iterative_solver.early_restart=0.1
```

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark submitted</summary>

```json
{
    "id": "0f71b6c1-e2ad-4273-b5fb-3fec3c037488",
    "reference": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "haampie/SIRIUS",
        "sha": "a923c3c8853d846138a8b9a9c096494004b8d208",
        "build": false
    },
    "current": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf",
            "--iterative_solver.early_restart=0.1"
        ],
        "repo": "haampie/SIRIUS",
        "sha": "adff978c05fe0b8ea67eae5f2174d5616f15acab",
        "build": false
    },
    "report_to": {
        "repository": "haampie/SIRIUS",
        "type": "pr",
        "issue": 4
    }
}

```
</details>

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/16/adff978_vs_a923c3c-43ae7ba7/

```diff
  Si63Ge ───────────────────  71.50 s  →  72.35 s   (+1.19%)
  SiO2-ANA-kpoint-parallel ─ no timings available
  SiO2-ANA-band-parallel ─── no timings available
```

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/16/adff978_vs_a923c3c-cf98e039/

```diff
  Si63Ge ───────────────────  71.53 s  →  70.19 s   (-1.87%)
  SiO2-ANA-kpoint-parallel ─ no timings available
  SiO2-ANA-band-parallel ─── no timings available
```

**Comment by haampie** [comment]
@electronic-structure run

```yaml
id: 0f71b6c1-e2ad-4273-b5fb-3fec3c037488

current:
  cmd: sirius.scf --iterative_solver.early_restart=0.5
```

**Comment by electronic-structure** [comment]
<details>
<summary>Benchmark <code>benchmarks/3277aa6</code> submitted:</summary>

```json
{
    "id": "0f71b6c1-e2ad-4273-b5fb-3fec3c037488",
    "reference": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "haampie/SIRIUS",
        "sha": "a923c3c8853d846138a8b9a9c096494004b8d208",
        "build": false
    },
    "current": {
        "spec": "sirius@develop",
        "cmd": [
            "sirius.scf",
            "--iterative_solver.early_restart=0.5"
        ],
        "repo": "haampie/SIRIUS",
        "sha": "adff978c05fe0b8ea67eae5f2174d5616f15acab",
        "build": false
    },
    "report_to": {
        "repository": "haampie/SIRIUS",
        "type": "pr",
        "issue": 4
    }
}

```
</details>

**Comment by electronic-structure** [comment]
Report for `benchmarks/fe2f96d6` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/17/adff978_vs_a923c3c-fe2f96d6/

```diff
  Si63Ge ───────────────────  72.03 s  →  72.37 s   (+0.47%)
  Au-surf ────────────────── no timings available
  SiO2-ANA-kpoint-parallel ─ 134.48 s  → 129.08 s   (-4.01%)
  SiO2-ANA-band-parallel ─── 235.33 s  → 224.54 s   (-4.59%)
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/f00ace21` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/18/adff978_vs_a923c3c-f00ace21/

```diff
  Si63Ge ───────────────────  71.82 s  →  72.66 s   (+1.18%)
+ Au-surf ────────────────── 281.02 s  → 230.65 s  (-17.93%)
  SiO2-ANA-kpoint-parallel ─ 125.11 s  → 128.88 s   (+3.01%)
  SiO2-ANA-band-parallel ─── 243.96 s  → 224.21 s   (-8.10%)
```

**Comment by electronic-structure** [comment]
Report for `benchmarks/f7855aac` at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/18/adff978_vs_a923c3c-f7855aac/

```diff
  Si63Ge ───────────────────  71.96 s  →  72.84 s   (+1.22%)
  Au-surf ────────────────── 188.01 s  → 172.03 s   (-8.50%)
  SiO2-ANA-kpoint-parallel ─ 133.09 s  → 128.52 s   (-3.43%)
  SiO2-ANA-band-parallel ─── 246.82 s  → 224.03 s   (-9.24%)
```

**Pull request merged**
