### PR TITLE
Disable locking by default

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Comment by haampie** [comment]
@electronic-structure run

```yaml
spec: sirius@develop +scalapack
```

**Comment by electronic-structure** [comment]
Benchmark started with the following settings:

```json
{
    "reference": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "haampie/SIRIUS",
        "sha": "58f31ed08f2b4e9e6d289f9ed116027f00413e03"
    },
    "current": {
        "spec": "sirius@develop +scalapack",
        "cmd": [
            "sirius.scf"
        ],
        "repo": "haampie/SIRIUS",
        "sha": "eab7a5e09a790e571ffec2b67e8d778bf317b1b5"
    },
    "report_to": {
        "repository": "haampie/SIRIUS",
        "type": "pr",
        "issue": 2
    }
}

```

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/haampie/SIRIUS-bench-reports/tree/master/58f31ed08f2b4e9e6d289f9ed116027f00413e03_vs_eab7a5e09a790e571ffec2b67e8d778bf317b1b5/

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/haampie/SIRIUS-bench-reports/tree/master/2020-10/12/eab7a5e_vs_58f31ed/

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/haampie/SIRIUS-bench-reports/tree/master/2020-10/12/eab7a5e_vs_58f31ed/

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/13/eab7a5e_vs_58f31ed/

- *Si63Ge*: 71.87 s  → 81.19 s  (+12.97%)
- *SiO2-ANA-kpoint-parallel*: no timings available
- *SiO2-ANA-band-parallel*: no timings available

**Comment by electronic-structure** [comment]
Benchmark report available at https://github.com/electronic-structure/SIRIUS-bench-reports/tree/master/2020-10/13/eab7a5e_vs_58f31ed/

```diff
- Si63Ge ───────────────────  71.75 s  →  81.41 s  (+13.47%)
  SiO2-ANA-kpoint-parallel ─ no timings available
  SiO2-ANA-band-parallel ─── no timings available
```

**Pull request closed without merging**
